# Generated by Django 3.1.2 on 2021-01-30 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='good',
            field=models.IntegerField(default=True),
        ),
    ]
