# Generated by Django 3.1.2 on 2021-01-30 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_report_good'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='good',
            field=models.IntegerField(blank=True, default=True),
        ),
    ]
