# Generated by Django 3.1.2 on 2021-01-30 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_report_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('h', 'hide'), ('d', 'Published'), ('w', 'Withdrawn')], default='', max_length=1),
        ),
    ]
