# Generated by Django 3.1.2 on 2021-01-31 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_remove_report_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='date_added',
        ),
    ]
